name: Test
on:
  push:

env:
  CARGO_TERM_COLOR: always
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            store = /home/runner/nix
            keep-outputs = true
            keep-derivations = true
            substituters = https://cache.nixos.org https://cache.nixos.org/ https://ai.cachix.org https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ai.cachix.org-1:N9dzRK+alWwoKXQlnn0H6aUx0lU/mspIoz8hMvGvbbc= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Run Tests
        run: |
          nix develop .
          cargo install cargo-odra --locked
          cargo odra test
